import { getClient } from "@/client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import Link from "next/link";
import { redirect } from "next/navigation";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  async function logOut() {
    "use server";
    cookies().delete("Authorization");
  }

  const isLoggedInResponse = await getClient().GET("/is-logged-in", {
    parseAs: "text",
  });

  const isLoggedIn = isLoggedInResponse.data === "Yes";

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-between">
          <div className="flex justify-start items-center">
            <Link href="/" className="bg-slate-600">
              Home
            </Link>
            <form
              className="flex gap-2 p-2"
              action={async function (formData: FormData) {
                "use server";
                const searchTerm = formData.get("search")?.toString();
                redirect(`/search/${searchTerm}`);
              }}
            >
              <input
                type="text"
                name="search"
                required
                className="text-black"
              />
              <button type="submit">Search</button>
            </form>
          </div>
          {isLoggedIn ? (
            <div className="flex justify-end items-center gap-2">
              <Link href="/my-books" className="bg-slate-600">
                My Books
              </Link>
              <form action={logOut}>
                <button type="submit" className="bg-red-500 p-2">
                  Log out
                </button>
              </form>
            </div>
          ) : (
            <Link href="/signup" className="bg-slate-600">
              Sign In / Sign Up
            </Link>
          )}
        </div>
        {children}
      </body>
    </html>
  );
}
